name: '[Develop] Deploy Functions'

env:
  COMPANY_NAME: ${{ vars.COMPANY_NAME }}
  TWITTER_CREATOR: ${{ vars.TWITTER_CREATOR }}
  TWITTER_SITE: ${{ vars.TWITTER_SITE }}
  SITE_NAME: ${{ vars.SITE_NAME }}
  SHOPIFY_REVALIDATION_SECRET: ${{ secrets.SHOPIFY_REVALIDATION_SECRET }}
  SHOPIFY_STOREFRONT_ACCESS_TOKEN: ${{ vars.SHOPIFY_STOREFRONT_ACCESS_TOKEN }}
  SHOPIFY_STORE_DOMAIN: ${{ vars.SHOPIFY_STORE_DOMAIN }}

on:
  push:
    branches:
      - develop

jobs:
  deploy-to-gcp:
    runs-on: ubuntu-latest
    environment: develop
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Create Service declaration
        run: |-
          export COMPANY_NAME="${{ env.COMPANY_NAME }}"
          export TWITTER_CREATOR="${{ env.TWITTER_CREATOR }}"
          export TWITTER_SITE="${{ env.TWITTER_SITE }}"
          export SITE_NAME="${{ env.SITE_NAME }}"
          export SHOPIFY_REVALIDATION_SECRET="${{ env.SHOPIFY_REVALIDATION_SECRET }}"
          export SHOPIFY_STOREFRONT_ACCESS_TOKEN="${{ env.SHOPIFY_STOREFRONT_ACCESS_TOKEN }}"
          export SHOPIFY_STORE_DOMAIN="${{ env.SHOPIFY_STORE_DOMAIN }}"
          envsubst < ./service-yaml/container.yaml > container-develop.yaml
          cat container-develop.yaml
      - name: Checkout repository
        uses: 'actions/checkout@v4'

      - name: Authenticate with Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          project_id: ${{ vars.PROJECT_ID }}
          credentials_json: ${{secrets.CREDENTIALS_JSON}}

      # https://github.com/marketplace/actions/deploy-to-cloud-run
      - name: Build and Deploy to Google CloudRun
        id: 'deploy'
        uses: 'google-github-actions/deploy-cloudrun@v2'
        with:
          service: ${{ vars.APP_NAME }}
          project_id: ${{ vars.PROJECT_ID }}
          region: ${{ vars.REGION }}
          source: ./
          metadata: container-develop.yaml

      - name: 'Use output'
        run: 'curl "${{ steps.deploy.outputs.url }}"'
